# Generated by Django 5.0 on 2026-05-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantmodel',
            name='gst_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='tenantmodel',
            name='registered_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantmodel',
            name='registration_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
