# Generated by Django 5.0 on 2026-04-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_clauselibraryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewcontract',
            name='contract_type',
            field=models.CharField(choices=[('nda', 'Non-Disclosure Agreement'), ('service_agreement', 'Service Agreement'), ('employment', 'Employment Agreement'), ('purchase', 'Purchase Agreement'), ('license', 'License Agreement'), ('lease', 'Lease Agreement'), ('partnership', 'Partnership Agreement'), ('loan', 'Loan Agreement'), ('vendor', 'Vendor Agreement'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='reviewcontract',
            name='review_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reviewcontract',
            name='review_status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('flags_raised', 'Flags Raised')], db_index=True, default='pending_review', max_length=32),
        ),
        migrations.AddField(
            model_name='reviewcontract',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewcontract',
            name='reviewer_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
