# Generated by Django 5.0 on 2026-02-12

import django.contrib.postgres.indexes
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0002_searchanalyticsmodel_searchindexmodel_indexed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchindexmodel",
            name="embedding",
            field=models.JSONField(blank=True, null=True),
        ),

        migrations.AddIndex(
            model_name="searchindexmodel",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"],
                name="search_title_trgm_gin",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
